version: '2'

services:
  drupal:
    image: xmonit/drupal8-apache:8.7.2
    restart: unless-stopped
    environment:
      - ENABLE_RPAF_MODULE=true
    ports:
      - 8080:80
    volumes:
      - ./mounts/ssmtp:/etc/ssmtp
      - /var/backups/drupal:/var/backups/drupal
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
      - drupal-libraries:/var/www/html/libraries
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mounts/sites/default/settings.php:/var/www/html/sites/default/settings.php
      - ./mounts/themes/xmonit:/var/www/html/themes/xmonit
    #command: sleep 10000
    links:
      - mysql

  mysql:
    image: mariadb:10.4.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: {password-here}
      MYSQL_USER: drupal
      MYSQL_PASSWORD: {password-here}
      MYSQL_DATABASE: drupal
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  drupal-modules:
    driver: local
  drupal-profiles:
    driver: local
  drupal-themes:
    driver: local
  drupal-sites:
    driver: local
  drupal-libraries:
    driver: local
  mysql-data:
    driver: local
  mysql-config:
    driver: local

  
  
  
  
  
  
