version: '2'

services:
  drupal:
    image: xmonit/drupal8-apache:8.7.7
    restart: unless-stopped
    environment:
      - ENABLE_RPAF_MODULE=true
    ports:
      - 8080:80
    volumes:
      - ./mounts/msmtp/msmtprc:/etc/msmtprc
      - ./mounts/msmtp/aliases:/etc/msmtp/aliases
      - /var/backups/drupal:/var/backups/drupal
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
      - drupal-libraries:/var/www/html/libraries
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mounts/sites/default/settings.php:/var/www/html/sites/default/settings.php
      - ./mounts/themes/xmonit:/var/www/html/themes/xmonit
    links:
      - mysql

  mysql:
    image: linuxserver/mariadb:arm32v7-110.3.18mariabionic-ls34
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: [root password here] 
      MYSQL_USER: [user here] 
      MYSQL_PASSWORD: [password here] 
      MYSQL_DATABASE: drupal
    volumes:
      - mysql:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  drupal-modules:
    driver: local
  drupal-profiles:
    driver: local
  drupal-themes:
    driver: local
  drupal-sites:
    driver: local
  drupal-libraries:
    driver: local
  mysql:
    driver: local
  
  
  
  
  
  
